apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-sendgrid-api
spec:
  hosts:
  - api.sendgrid.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: messaging-email
  namespace: bicycle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-email
  template:
    metadata:
      labels:
        app: messaging-email
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: messaging-email
        image: eu.gcr.io/rso-bicycle/messaging-email:master
        imagePullPolicy: Always
        env:
        - name: SERVICE_KAFKA_BROKERADDR
          value: "kafka.system:9092"
        - name: SERVICE_EMAIL_FROMADDRESS
          value: "test@rso-bicycle.si"
        - name: SERVICE_EMAIL_FROMNAME
          value: "RSO Bicycle"
        - name: SERVICE_SENDGRID_APIKEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-apikey
              key: key